--- # PlayLabs 
- hosts: lab
  connection: ssh
  remote_user: ansible
  become: yes
  gather_facts: yes

  vars:
    author: git@mtulio.eng.br
    refs: 
      - https://github.com/jaywink/ansible-letsencrypt

  roles:
    - role: letsencrypt
      letsencrypt_email: 'root@mtulio.eng.br'
      letsencrypt_domain: 'ict-eng.net'
      letsencrypt_domain_flags:
        - "-d www.ict-eng.net"
        - "-d app.ict-eng.net"
      letsencrypt_pause_services:
        - nginx
