--- # LAB: Runonce tasks
- hosts: all
  user: ansible
  sudo: yes
  connection: ssh
  gather_facts: no
  vars:
    author: Marco Tulio R Braga <git@mtulio.eng.br>
  tasks:
    - name: Run the uptime command on all hosts and log it
      raw: /usr/bin/uptime >> /tmp/uptime.log
    # Run once the first hosts found. check first at:  ansible all --list-hosts
    - name: List the /var dir and log it 
      raw: ls -al /var >> /tmp/dir.list
      run_once: true 
