--- # LAB
- name: LAB - Create User
  hosts: all:!127.0.0.1
  connection: ssh
  remote_user: ansible
  become: yes
  gather_facts: no
  vars:
    author: Marco Tulio R Braga <git@mtulio.eng.br>
  tasks:
    - name: Create USER and its directory
      user:
        name: user1
        state: present
        home: /tmp/user1
        shell: /bin/nologin
        createhome: yes
      register: ret_val

    - name: Debug Create USER
      debug: msg={{ret_val.rc}}
      when: ret_val is defined  
