--- # Launch EC2 Instances
- name: Launch EC2 Instances
  hosts: localhost
  connection: local
  remote_user: ansible
  become: no
  gather_facts: no

  vars:

  tasks:

  # Note: These examples do not set authentication details, see the AWS Guide for details.

  # Get a session token (more details: http://docs.aws.amazon.com/STS/latest/APIReference/API_GetSessionToken.html)
  - sts_session_token:
      duration: 3600
    register: session_credentials

  - debug: msg="{{session_credentials}}"

  # Use the session token obtained above to tag an instance in account 123456789012
#  ec2_tag:
#    aws_access_key: "{{ session_credentials.sts_creds.access_key }}"
#    aws_secret_key: "{{ session_credentials.sts_creds.secret_key }}"
#    security_token: "{{ session_credentials.sts_creds.session_token }}"
#    resource: i-xyzxyz01
#    state: present
#    tags:
#      MyNewTag: value
