--- # PlayLab 
- name: AWS Playbook Lab
  hosts: localhost
  connection: local
  remote_user: ansible
  become: yes
  gather_facts: no

  vars:
    aws:
      region: us-west-2

  vars_files:
    - keys/aws_cred.yml

  tasks:
  - name: Label an existing volume so we know what it is
    ec2_tags:
      aws_access_key: "{{ aws_id }}"
      aws_secret_key: "{{ aws_key }}" 
      region: "{{ aws.region }}"
      wait: no
      resource: vol-xxxxxxx
      state: present
      tags:
        Name: data_volume01
    register: ret_ec2

  - debug: msg={{ ret_ec2 }}
