--- # AWS VPC
- name: Create AWS VPC [using jinja2]
  hosts: localhost
  connection: local
  remote_user: ansible
  become: yes
  gather_facts: no

  vars:
    aws:
      region: us-west-2

  vars_files:
    - keys/aws_cred.yml

  tasks:
  - name: Creating all VPC
    with_items: "{{vpc}}"
    ec2_ami:
      aws_access_key: "{{ aws_id }}"
      aws_secret_key: "{{ aws_key }}" 
      region: "{{ aws.region }}"
      instance_id: 
      wait: no
      name: MyNewAmi
      tags:
        Name: MyNewAmi
        service: TestAMIService
    register: ret_ec2_ami
