--- # Lab Course
- name: Configure EC2 Alarm
  hosts: localhost
  connection: local
  remote_user: ansible
  become: yes
  gather_facts: no

  vars:
    aws:
      region: us-west-2

  vars_files:
    - keys/aws_cred.yml

  tasks:
  - name: Configure EC2 Alarm
    ec2_metric_alarm:
      aws_access_key: "{{ aws_id }}"
      aws_secret_key: "{{ aws_key }}" 
      region: "{{ aws.region }}"
      state: present
      name: FistAlarmTest
      metric: "CPUUtilization"
      namespace: "AWS/EC2"
      statistic: Average
      omparison: ">="
      threshold: 25.0
      period: 300
      evalution_periods: 6
      unit: "Percent"
      description: "This alarm fires when CPU is greater than 25% for 30 minutes"
      dimensions: {'InstanceID': 'i-xxxxx' }
      #alarm_actions: ["EmailTo"]
    register: ret_ec2
