--- # PlayLab 
- name: AWS Playbook Lab
  hosts: localhost
  connection: local
  remote_user: ansible
  become: yes
  gather_facts: no

  vars:
    aws:
      region: us-west-2

  vars_files:
    - keys/aws_cred.yml

  tasks:
  - name: Create an S3 Bucket
    s3:
      aws_access_key: "{{ aws_id }}"
      aws_secret_key: "{{ aws_key }}" 
      region: "{{ aws.region }}"
      bucket: mtulio-ansible
      mode: create
      permission: public-read-write
    register: ret_s3_create

  - name: Copy files to the Bucket
    s3:
      aws_access_key: "{{ aws_id }}"
      aws_secret_key: "{{ aws_key }}" 
      region: "{{ aws.region }}"
      bucket: mtulio-ansible
      object: /Playbooks/lab_aws_s3.yml
      src: ./Playlabs/lab_aws_s3.yml
      mode: put
    register: ret_s3_put

  - name: Output creation
    debug: var=ret_s3_create
  
  - name: Output put
    debug: var=ret_s3_put
