--- # AWS AMI Custom
- name: Create AWS AMI Custom
  hosts: localhost
  connection: local
  remote_user: ansible
  become: yes
  gather_facts: no

  vars:
    aws:
      region: us-west-2

  vars_files:
    - keys/aws_cred.yml

  tasks:
  - name: Advanced AMI creating Custom from our Instance
    with_items: "{{vpc}}"
    ec2_ami:
      aws_access_key: "{{ aws_id }}"
      aws_secret_key: "{{ aws_key }}" 
      region: "{{ aws.region }}"
      instance_id: 
      wait: no
      name: MyNewAmi
      tags:
        Name: MyNewAmi
        service: TestAMIService
      device_mapping:
        - device_name: /dev/sdb1
          size: 100
          delete_on_termination: true
          volume_type: gp2
    register: ret_ec2_ami
