--- # PlayLab 
- name: AWS Playbook Lab
  hosts: localhost
  connection: local
  remote_user: ansible
  become: yes
  gather_facts: no

  vars:
    aws:
      region: us-west-2

  vars_files:
    - keys/aws_cred.yml

  tasks:
  - name: Create a VPC
    ec2_vpc_net:
      aws_access_key: "{{ aws_id }}"
      aws_secret_key: "{{ aws_key }}" 
      region: "{{ aws.region }}"
      wait: no
      name: MyNewVPC
      state: present
      cidr_block: 172.17.1.0/24
    register: ret_ec2


  - name: Print the resulting JSON output
    debug: msg={{ ret_ec2 }}
