--- # PlayLab 
- name: AWS Playbook Lab
  hosts: localhost
  connection: local
  remote_user: ansible
  become: yes
  gather_facts: no

  vars:
    aws:
      region: us-west-2

  vars_files:
    - keys/aws_cred.yml

  tasks:
  - name: Gather remote facts of all running EC2 instances
    ec2_remote_facts:
      aws_access_key: "{{ aws_id }}"
      aws_secret_key: "{{ aws_key }}" 
      region: "{{ aws.region }}"
    register: ret_ec2

  - debug: msg={{ ret_ec2 }}
